# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: template
    sensors:
      temperature_sensor:
        friendly_name: 'Czujnik temperatury'
        unit_of_measurement: '°C'
        value_template: "{{ states('sensor.sht35_temperature') }}"

  - platform: template
    sensors:
      pulse_sensor:
        friendly_name: 'Czujnik tętna'
        unit_of_measurement: 'BPM'
        value_template: "{{ states('sensor.max30102_pulse') }}"

  - platform: template
    sensors:
      ecg_sensor:
        friendly_name: 'Czujnik EKG'
        unit_of_measurement: 'mV'
        value_template: "{{ states('sensor.ad8232_ecg') }}"

  - platform: template
    sensors:
      spo2_sensor:
        friendly_name: 'Czujnik SPO2'
        unit_of_measurement: '%'
        value_template: "{{ states('sensor.max30102_spo2') }}"
